//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentManagement()
        {
            this.EquipmentSchedules = new HashSet<EquipmentSchedule>();
            this.EquipmentValues = new HashSet<EquipmentValue>();
        }
    
        public string id_equipment { get; set; }
        public string id_esp { get; set; }
        public string name_equipment { get; set; }
        public Nullable<int> automode { get; set; }
        public string id_sensor { get; set; }
    
        public virtual Esp Esp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSchedule> EquipmentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentValue> EquipmentValues { get; set; }
    }
}
