//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentValueLog
    {
        public int id { get; set; }
        public string id_equipment { get; set; }
        public Nullable<double> values { get; set; }
        public double status { get; set; }
    }
}
