//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSchedule
    {
        public int id { get; set; }
        public string id_equipment { get; set; }
        public Nullable<int> times_offset { get; set; }
        public Nullable<System.TimeSpan> times { get; set; }
    
        public virtual EquipmentManagement EquipmentManagement { get; set; }
    }
}
