//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esp()
        {
            this.EquipmentManagements = new HashSet<EquipmentManagement>();
            this.SensorManagements = new HashSet<SensorManagement>();
        }
    
        public string id_esp { get; set; }
        public string id_user { get; set; }
        public string name_esp { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string decription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentManagement> EquipmentManagements { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorManagement> SensorManagements { get; set; }
    }
}
