//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ngunemay123_SampleDBEntities7 : DbContext
    {
        public ngunemay123_SampleDBEntities7()
            : base("name=ngunemay123_SampleDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EquipmentManagement> EquipmentManagements { get; set; }
        public virtual DbSet<EquipmentSchedule> EquipmentSchedules { get; set; }
        public virtual DbSet<EquipmentValueLog> EquipmentValueLogs { get; set; }
        public virtual DbSet<EquipmentValue> EquipmentValues { get; set; }
        public virtual DbSet<Esp> Esps { get; set; }
        public virtual DbSet<SensorManagement> SensorManagements { get; set; }
        public virtual DbSet<SensorValue> SensorValues { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
