//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SensorManagement()
        {
            this.SensorValues = new HashSet<SensorValue>();
        }
    
        public string id_sensor { get; set; }
        public string id_esp { get; set; }
        public string name_sensor { get; set; }
        public Nullable<double> expectedValues { get; set; }
        public string min_max_values { get; set; }
    
        public virtual Esp Esp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorValue> SensorValues { get; set; }
    }
}
