//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorValue
    {
        public int id { get; set; }
        public string id_sensor { get; set; }
        public double value { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual SensorManagement SensorManagement { get; set; }
    }
}
